services:
  web:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=zlagoda_db
      - TZ=Europe/Kyiv
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zlagoda_db
      - TZ=Europe/Kyiv
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d zlagoda_db"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
